---
- name: Ensure routing table 23 exists and is called ffnw
  lineinfile:
    path: /etc/iproute2/rt_tables
    regexp: '^23\s+.*'
    line: '23 ffnw'
    state: present
  tags: ffnw

- name: Ensure GRE traffic is not blocked by firewall
  copy:
    src: etc/iptables.d/500-Allow-GRE
    dest: /etc/iptables.d/500-Allow-GRE
  notify:
    - restart firewall
  tags: ffnw

- name: Ensure gre tunnel config is in place
  template:
    src: etc/network/interfaces.d/ffnw-gre.j2
    dest: /etc/network/interfaces.d/ffnw-gre
  notify:
    - restart ffnw tunnel
  tags: ffnw
