---
- name: Ensure netfilter-persistent is installed
  apt:
    name: netfilter-persistent
    state: present

- name: Ensure firewall directory exists
  file:
    path: /etc/iptables.d
    state: directory

- name: Ensure firewall rules are deployed
  template:
    src: "{{ item }}"
    dest: /etc/iptables.d/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - ../templates/etc/iptables.d/*.j2
  notify:
    - restart firewall

- name: Ensure iptables service is enabled and started
  service:
    name: iptables
    enabled: yes
    state: started
