---
# This role configures the basic, always required interfaces
- name: ensure bridge interface is present
  template:
    src: etc/network/interfaces.d/bridge.j2
    dest: /etc/network/interfaces.d/br-{{ site.code }}
  notify:
    - restart mesh bridge 
    - restart batman

- name: ensure batman interface is present
  template:
    src: etc/network/interfaces.d/batman.j2
    dest: /etc/network/interfaces.d/bat-{{ site.code }}
  notify:
    - restart batman
