---
- name: Setup iproute2 related stuff
  import_tasks: iproute2.yml
  tags: iproute2, network

- name: Setup sysctl
  import_tasks: sysctl.yml
  tags: sysctl, network

- name: Install required packages
  import_tasks: packages.yml
  tags: packages

- name: Setup firewall
  import_tasks: firewall.yml
  tags: firewall, network

- name: Setup interfaces
  import_tasks: interfaces.yml
  tags: interfaces, network

- name: Setup radvd
  import_tasks: radvd.yml
  tags: radvd, network

- name: Setup mesh-announce
  import_tasks: mesh-announce.yml
  tags: mesh-announce, respondd
