---
# Repos
- name: Ensure universefactory debian repo is present
  copy:
    src: etc/apt/sources.list.d/repo.universe-factory.list
    dest: /etc/apt/sources.list.d/repo.universe-factory.list
  register: apt_source_uf

- name: Install universefactory key
  shell: apt-key adv --recv-keys --keyserver keys.gnupg.net 16EF3F64CB201D9C
  when: apt_source_uf.changed

# Pins
- name: Ensure apt pins are in place
  template:
    src: etc/apt/preferences.d/batman-adv-dkms
    dest: /etc/apt/preferences.d/batman-adv-dkms

# Packages
- name: Ensure packages are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - bridge-utils
    - batctl
    - netfilter-persistent
    - bird

# Phase out batman-adv to make result easily available
- name: Ensure batman-adv is installed
  apt:
    name: batman-adv-dkms
    state: present
  register: apt_batadv

# Batman-adv post-processing
- name: Fix dkms installation
  vars:
    kversion: "{{ batman.version | regex_replace('-[0-9]+$','') }}"
  shell: |
    dkms uninstall --force batman-adv/{{ kversion }} || true
    modinfo batman-adv | grep -i '^filename' | tr -d ' ' | cut -d: -f2 | xargs rm
    dkms install --force batman-adv/{{ kversion }}
  when:
    apt_batadv.changed
