---
- name: Ensure radvd is installed
  apt:
    name: radvd
    state: present
  notify:
    - restart radvd

- name: Ensure radvd config is in place
  template:
    src: etc/radvd.conf.j2
    dest: /etc/radvd.conf
  notify:
    - restart radvd

- name: Ensure radvd service is enabled
  service:
    name: radvd
    enabled: yes
    state: started
