---
- name: Ensure radvd is installed
  apt:
    name: radvd
    state: present
  notify:
    - restart radvd

- name: Ensure radvd fragment directory exist
  file:
    path: /etc/radvd.fragment.d/
    state: directory
  notify:
    - restart radvd

- name: Ensure radvd config fragments are in place
  template:
    src: "{{ item }}"
    dest: /etc/radvd.fragment.d/{{ item | basename | regex_replace('\.j2','') | regex_replace('{{\s*site.code\s*}}', site.code) }}
  with_fileglob:
    - ../templates/etc/radvd.fragment.d/*.j2
  notify:
    - restart radvd

- name: Ensure radvd config build is up to date
  assemble:
    src: /etc/radvd.fragment.d
    dest: /etc/radvd.conf
  notify:
    - restart radvd

- name: Ensure radvd service is enabled
  service:
    name: radvd
    enabled: yes
    state: started
