- name: Ensure unbound is installed
  apt:
    name: unbound
    state: present
  notify:
    - restart unbound

- name: Ensure unbound config file is in place
  template:
    src: etc/unbound/unbound.conf.j2
    dest: /etc/unbound/unbound.conf
  notify:
    - restart unbound

- name: Ensure unbound service is enabled and started
  service:
    name: unbound.service
    enabled: yes
    state: started
