---
- name: Ensure wireshark package is configured correctly
  debconf:
    name: wireshark-common
    question: wireshark-common/install-setuid
    vtype: boolean
    value: yes
  tags:
    - wirerrd

- name: Ensure required packages are installed
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - bc
    - tshark
    - pcaputils
    - rrdtool
    - inotify-tools
    - csvtool
    - opt
    - gnuplot
    - imagemagick
    - imagemagick-common
  tags:
    - wirerrd

- name: Ensure wirerrd user exists
  user:
    name: wirerrd
    groups: wireshark
    state: present
  tags:
    - wirerrd

- name: Ensure wirerrd rrd directory exists
  file:
    path: /home/wirerrd/rrd
    state: directory
    owner: wirerrd
    group: wirerrd
    mode: 0755
  tags:
    - wirerrd

- name: Ensure wirerrd git is cloned
  git:
    repo: https://github.com/sargon/wirerrd.git
    version: systemd
    dest: /home/wirerrd/wirerrd
    update: yes
  tags:
    - wirerrd

- name: Ensure wirerrd systemd templates are installed
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - ../templates/etc/systemd/system/*.j2
  register: wirerrd_templates
  tags:
    - wirerrd

- name: Ensure systemd services are reloaded if templates changed
  shell: systemctl daemon-reload
  when: wirerrd_templates.changed
  tags:
    - wirerrd

- name: Ensure wirerrd collect service is enabled
  service:
    name: wirerrd-collect.service
    enabled: yes
    state: restarted
  tags:
    - wirerrd

- name: Ensure wirerrd export timer is enabled
  service:
    name: wirerrd-export.timer
    enabled: yes
    state: restarted
  tags:
    - wirerrd
