---
- name: Ensure gateways are set up
  hosts: gateways
  roles:
    - gateway
    - mesh_vpn
  tags: gateway

- name: Ensure gateways are peered with ffnw via ipv6
  hosts: peering_ffnw6
  roles:
    - ffnw6
  tags: gateway
