---
- name: Ensure manual config for interface {{ iface }} exists
  template:
    src: '{{ "etc/network/interfaces.d/{{ iface }}.j2" }}'
    dest: /etc/network/interfaces.d/{{ iface }}
  notify:
    - restart manual interface
  tags: interface_manual
