---
# Interface config
- name: Ensure ffnw ipv4 peering interface config is in place
  template:
    src: etc/network/interfaces.d/ffnw-gre_nat.j2
    dest: /etc/network/interfaces.d/ffnw-gre_nat
  notify:
    - restart ffnw tunnel
  tags: ffnw4

- name: Ensure ffnw ipv4 transit networks are configured
  template:
    src: etc/network/interfaces.d/ffnw-gre_transit.j2
    dest: /etc/network/interfaces.d/ffnw-gre_transit
  notify:
    - restart ffnw tunnel
  tags: ffnw4

# bgp Peerings
- name: Ensure ffnw bgp4 peers are in place
  template:
    src: etc/bird/bird4.peers.d/ffnw.conf.j2
    dest: /etc/bird/bird4.peers.d/ffnw.conf
  notify:
    - configure bird
  tags: ffnw4

# bird config
- name: Ensure ffnw bgp4 kernel route filter is in place
  template:
    src: etc/bird/bird4.filters.d/mesh_kernel.d/050-ffnw-set-krt_prefsrc.export.j2
    dest: /etc/bird/bird4.filters.d/mesh_kernel.d/050-ffnw-set-krt_prefsrc.export
  notify:
    - configure bird
  tags: ffnw4

- name: Ensure ffnw bgp4 config defines are in place
  template:
    src: etc/bird/bird4.conf.d/020-ffnw-defines.conf.j2
    dest: /etc/bird/bird4.conf.d/020-ffnw-defines.conf
  notify:
    - configure bird
  tags: ffnw4

- name: Ensure ffnw bgp4 config is in place
  template:
    src: etc/bird/bird4.conf.d/200-ffnw.conf.j2
    dest: /etc/bird/bird4.conf.d/200-ffnw.conf
  notify:
    - configure bird
  tags: ffnw4

# Firewall
- name: Ensure SNAT is enabled on peering interfaces
  template:
    src: etc/iptables.d/910-SNAT-ffnw
    dest: /etc/iptables.d/910-SNAT-ffnw
  notify:
    - restart firewall
  tags: ffnw4
