---
- name: Ensure wireguard related firewall config is set up
  block:
  - name: Ensure input chain for wireguard is set up
    template:
      src: '{{ "etc/iptables.d/001-CHAINS-input_wg-{{ site.code }}.j2" }}'
      dest: /etc/iptables.d/001-CHAINS-input_wg-{{ site.code }}
    notify: restart firewall

  - name: Ensure delegation to wireguard input chain is set up
    template:
      src: '{{ "etc/iptables.d/100-device-wg-{{ site.code }}.j2" }}'
      dest: /etc/iptables.d/100-device-wg-{{ site.code }}
    notify: restart firewall
  when: 'wireguard is defined'
  tags: wireguard_p2p, firewall

- name: Ensure wireguard peerings are set up
  vars:
    wg_p2p_route_default: '{{ wireguard.p2p_route | default(False) }}'
    wg_peer: '{{ item.key }}'
    wg_iface: '{{ ("wg-" ~ site.code ~ "-" ~ (wg_peer | sha256)) | trunc(15) }}'
    wg_addr: '{{ item.value.address }}'
    wg_p2p_route: '{{ item.value.p2p_route | default(wg_p2p_route_default) }}'
    wg_local_port:  '{{ ("wg-" ~ site.code ~ "-" ~ inventory_hostname ~ wg_peer) | hashnum(site.wireguard.port_range.start, site.wireguard.port_range.end) }}'
    wg_remote_port: '{{ ("wg-" ~ site.code ~ "-" ~ wg_peer ~ inventory_hostname) | hashnum(site.wireguard.port_range.start, site.wireguard.port_range.end) }}'
    wg_ifpref: '{% if wireguard.ifpref is defined %}{{ wireguard.ifpref }}-{% else %}{% endif %}'
  include_tasks: peer.yml
  loop: '{{ wireguard.peers | dict2items }}'
  when: 'wireguard is defined'
  tags: wireguard_p2p
