---
dependencies:
  - role: router
  - role: firewall_mss_clamp
    vars:
      iface: wg-{{ site.code }}
      mss: 1350
  - role: wireguard_p2p
    vars:
      wireguard:
        peers: '{{ site_l3.peers }}'
        key:   '{{ site_l3.key }}'
      wireguard_alias: gateway_site_l3
  - { role: bird4 }
  - { role: bird6 }
  - role: dhcp_server
    vars:
      dhcp_iface: '{{ interface.lan.name }}'
      dhcp_network: '{{ interface.lan.address.ipv4 | ipaddr("0") }}'
      dhcp_options:
        routers: '{{ interface.lan.address.ipv4 | strip_prefixlen }}'
        domain-name-servers:
          - '{{ interface.lan.address.ipv4 | strip_prefixlen }}'
          - '{{ interface.lan.address.ipv4 | strip_prefixlen }}'
        domain-name: '"{{ site.tld if site.tld is defined else site.code }}"'
        ntp-servers: '{{ interface.lan.address.ipv4 | strip_prefixlen }}'
      dhcp_range: '{{ interface.lan.dhcp_range }}'
      dhcp_lease_time:
        min: 300
        default: 21600
        max: 86400
  - role: dns_iterator
    vars:
      dns_iface: '{{ interface.lan.name }}'
      dns_listen:
        - '{{ interface.lan.address.ipv4 | strip_prefixlen }}'
        - '{{ interface.lan.address.ipv6 | strip_prefixlen }}'
      dns_acl:
        - '{{ interface.lan.address.ipv4 | ipaddr("0") }}'
        - '{{ interface.lan.address.ipv6 | ipaddr("0") }}'
      dns_zones: '{{ site.dns | merge({ ".": site_l3.dns }) }}'
