---
dependencies:
  - role: router
  - role: firewall_mss_clamp
    vars:
      iface: wg-{{ site.code }}
      mss: 1350
  - role: wireguard_p2p
    vars:
      wireguard:
        peers: '{{ site_l3.peers }}'
        key:   '{{ site_l3.key }}'
      wireguard_alias: gateway_site_l3
  - { role: bird4 }
  - { role: bird6 }
