---
- name: Ensure bird is installed
  apt:
    name: bird
    state: present
  notify:
    - restart bird6
  tags: bgp6

- name: Ensure bird6 config directory exists
  file:
    path: /etc/bird/bird6.conf.d
    state: directory
  notify:
    - restart bird6
  tags: bgp6

- name: Ensure bird6 peer directory exists
  file:
    path: /etc/bird/bird6.peers.d
    state: directory
  notify:
    - restart bird6
  tags: bgp6

- name: Ensure bird6 config exists
  template:
    src: etc/bird/bird6.conf.j2
    dest: /etc/bird/bird6.conf
  notify:
    - configure bird6
  tags: bgp6

- name: Ensure bird6 mesh peering config exists
  template:
    src: "{{ 'etc/bird/bird6.peers.d/{{ site.code }}.conf.j2' }}"
    dest: "/etc/bird/bird6.peers.d/{{ site.code }}.conf"
  notify:
    - configure bird6
  tags: bgp6

- name: Ensure bird6 mesh config exists
  template:
    src: "{{ 'etc/bird/bird6.conf.d/{{ site.code }}.conf.j2' }}"
    dest: "/etc/bird/bird6.conf.d/{{ site.code }}.conf"
  notify:
    - configure bird6
  tags: bgp6

- name: Ensure firewall allows bgp traffic
  copy:
    src: etc/iptables.d/500-Allow-bird-ipv6
    dest: /etc/iptables.d/500-Allow-bird-ipv6
  notify:
    - restart firewall
  tags: bgp6

- name: Ensure bird6 service is enabled
  service:
    name: bird6
    enabled: yes
    state: started
  tags: bgp6
