---
- name: restart firewall
  service:
    name: iptables
    state: restarted
  listen: 'restart network'

- name: reload sysctl
  shell: sysctl --system

- name: restart ntp
  service:
    name: ntp
    state: restarted
