---
# Prerequisites
- name: Ensure fastd is installed
  apt:
    name: fastd
    state: present
  notify:
    - restart fastd
  tags: mesh_vpn

- name: Ensure git is installed
  apt:
    name: git
    state: present
  tags: mesh_vpn

- name: Ensure patch is installed
  apt:
    name: patch
    state: present
  tags: mesh_vpn

- name: Ensure firewall allows fastd traffic
  copy:
    src: etc/iptables.d/500-Allow-fastd
    dest: /etc/iptables.d/500-Allow-fastd 
  notify:
    - restart firewall
  tags: mesh_vpn

# Config 
- name: Ensure fastd peer directory exists
  file:
    path: "/etc/fastd/mvpn-{{ site.code }}/peers"
    state: directory
  notify:
    - restart fastd
  tags: mesh_vpn

- name: Ensure fastd config exists
  template:
    src: etc/fastd/mvpn/fastd.conf.j2
    dest: "/etc/fastd/mvpn-{{ site.code }}/fastd.conf"
  notify:
    - restart fastd
  tags: mesh_vpn

# Peers
- name: Ensure fastd key repo is up to date
  git:
    repo: "{{ site.mesh_vpn.key_git }}"
    dest: "/etc/fastd/mvpn-{{ site.code }}/peers"
    force: yes
  tags: mesh_vpn, fastd_keys

# Service
- name: Ensure fastd init file is patched
  patch:
    src: patches/0000-fastd-init-wait-for-process.patch
    dest: /etc/init.d/fastd
    basedir: /
  notify:
    - restart fastd
  tags: mesh_vpn

- name: Ensure fastd service is enabled and started
  service:
    name: fastd.service
    enabled: yes
    state: started
  tags: mesh_vpn
