---
dependencies:
  - { role: ffnw }
  - { role: bgp6 }
  - role: radvd
    vars:
      ra_iface: br-{{ site.code }}
      ra_default_lifetime: 1200
      ra_prefixes:
        - prefix: '{{ interface.mesh_bridge.ffnw.ipv6 | ipaddr("network/prefix") }}'
          lifetime:
            preferred: 300
            valid: 600
