---
- name: Setup sysctl
  import_tasks: sysctl.yml
  tags: node_l2, sysctl, network

- name: Setup firewall
  import_tasks: firewall.yml
  tags: node_l2, firewall, network

- name: Setup interfaces
  import_tasks: interfaces.yml
  tags: node_l2, interfaces, network
