---
- name: Setup sysctl
  import_tasks: sysctl.yml
  tags: sysctl, network

- name: Setup firewall
  import_tasks: firewall.yml
  tags: firewall, network

- name: Setup interfaces
  import_tasks: interfaces.yml
  tags: interfaces, network
