---
- name: rebuild radvd config
  assemble:
    src: /etc/radvd.fragment.d
    dest: /etc/radvd.conf

- name: restart radvd
  service:
    name: radvd
    state: restarted

- name: restart respondd
  service:
    name: respondd
    state: restarted

- name: restart dhcpd
  service:
    name: isc-dhcp-server
    state: restarted
  listen: 'restart mesh bridge'

- name: restart unbound
  service:
    name: unbound
    state: restarted

- name: restart bind
  service:
    name: bind9
    state: restarted

- name: restart prometheus-node-exporter
  service:
    name: prometheus-node-exporter
    state: restarted
