---
- name: restart firewall
  service:
    name: iptables
    state: restarted
  listen: 'restart network'

- name: restart mesh bridge
  shell: |
    ifdown br-{{ site.code }} || ( ip link set down br-{{ site.code }} && brctl delbr br-{{ site.code }} ) || true
    ifup br-{{ site.code }}
  listen: 'restart network'

- name: restart batman
  shell: |
    ifdown bat-{{ site.code }} || ip link set down bat-{{ site.code }} || true
    ifup bat-{{ site.code }}
  listen: 'restart network'

- name: restart radvd
  service:
    name: radvd
    state: restarted

- name: reload sysctl
  shell: sysctl --system

- name: restart respondd
  service:
    name: respondd
    state: restarted

- name: restart dhcpd
  service:
    name: isc-dhcp-server
    state: restarted

- name: restart unbound
  service:
    name: unbound
    state: restarted

- name: restart ntp
  service:
    name: ntp
    state: restarted

- name: restart bind
  service:
    name: bind9
    state: restarted

- name: restart prometheus-node-exporter
  service:
    name: prometheus-node-exporter
    state: restarted
