---
# Repos
- name: Ensure universefactory debian repo is present
  copy:
    src: etc/apt/sources.list.d/repo.universe-factory.list
    dest: /etc/apt/sources.list.d/repo.universe-factory.list

- name: Install universefactory key
  shell: apt-key adv --recv-keys --keyserver keys.gnupg.net 16EF3F64CB201D9C

# Pins
- name: Ensure apt pins are in place
  template:
    src: etc/apt/preferences.d/batman-adv-dkms
    dest: /etc/apt/preferences.d/batman-adv-dkms

# Packages
- name: Ensure packages are installed
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - bridge-utils
    - batman-adv-dkms
    - batctl

# Batman-adv post-processing
- name: Fix dkms installation
  vars:
    kversion: "{{ batman.version | regex_replace('-[0-9]+$','') }}"
  shell: |
    dkms uninstall --force batman-adv/{{ kversion }} || true
    modinfo batman-adv | grep -i '^filename' | tr -d ' ' | cut -d: -f2 | xargs rm
    dkms install --force batman-adv/{{ kversion }}
