---
- name: restart wireguard
  vars:
    wg_iface: '{{ ("wg-" ~ site.code ~ "-" ~ (item.key | sha256)) | trunc(15) }}'
  shell: |
    ifdown {{ wg_iface }} || ( ip link set down {{ wg_iface }} && ip link del {{ wg_iface }} ) || true
    ifup {{ wg_iface }}
  loop: '{{ wireguard.peers | dict2items }}'
